load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "core",
    srcs = ["gemini_service.py"],
    visibility = ["//visibility:public"],
    deps = [
        "//python/common/observability",
        # "@pypi//google_genai",
    ],
)
